### ISSUE TITLE
MenuV:OpenMenu doesnt work

### ISSUE THREAD

**Issue by Nevos08** [ThymonA/menuv#11]
https://prnt.sc/vzom1g

https://prnt.sc/vzom5a

**Comment by ThymonA** [comment]
I don't have any issues on the latest version **1.3**, your issue isn't reproducible.
Make sure **MenuV** is inside your resource folder and add `start menuv` above the resources using **MenuV**
I tried your code in an example resource, tested resource -> [menuv_example.zip](https://github.com/ThymonA/menuv/files/5672386/menuv_example.zip)

**Proof:**
![MenuV Example](https://i.imgur.com/vic68an.jpg)

**Comment by Nevos08** [comment]
Hm. This is my start order: https://prnt.sc/vztp1d
And this is the full code: https://prnt.sc/vztps3

**Comment by ThymonA** [comment]
@Nevos08 Did you downloaded the latest release version or the `master` version?

**Comment by Nevos08** [comment]
Release.
I tried to open the menu via OpenWith and it worked. I dont know if its just this one function
