### ISSUE TITLE
How do I define a uuid to a menu?

### ISSUE THREAD

**Issue by iWanheda** [ThymonA/menuv#12]
Didn't find it on docs...

**Comment by ThymonA** [comment]
UUID is always random and generated dynamically. UUID should only be used as a getter and shouldn't be set manually. UUID is used to identify a specific item or menu without checking them in dept. 

https://github.com/ThymonA/menuv/blob/58883252d278a0b5dee498975244cda0a247ac98/app/lua_components/menu.lua#L302 is calling this: https://github.com/ThymonA/menuv/blob/58883252d278a0b5dee498975244cda0a247ac98/app/lua_components/utilities.lua#L334-L369

UUID is automatically handled by MenuV itself and shouldn't be done manually.

**Comment by iWanheda** [comment]
Then how do I get a specific menu if I don’t know it’s uuid

Thymon Arens <notifications@github.com> escreveu em sáb, 12/12/2020 às
12:15 :

**Comment by ThymonA** [comment]
Can you write an example when you need to open an unknown menu?

**Comment by ThymonA** [comment]
Contact with `dopamine#1337` on Discord, will close this issue for now.
