### ISSUE TITLE
assertion failed!

### ISSUE THREAD

**Issue by chopo156** [ThymonA/menuv#14]
Hi thymon! your awesome!, i have the title error in almost every resource, i just add the code to open the menu and that shows up, tested de menuv_example and the menu open

**Comment by chopo156** [comment]
It was the fxmaifest sorry!

**Comment by Melrpm** [comment]
Share what was your issue

**Comment by Melrpm** [comment]
You must include @menuv before your client lua file!

client_scripts {
    '@menuv/menuv.lua',
    'client.lua'
}
