### ISSUE TITLE
Example Menu not working

### ISSUE THREAD

**Issue by TopZoozle** [ThymonA/menuv#17]
Attempted to use the example menu just to get a feel for the menu itself and instantly ran into this ( Built the newest version )

[Screenshot](https://prnt.sc/weq91j)

Just wanted to let you know.

**Comment by ThymonA** [comment]
You can't add `example.lua` inside the `menuv` resource itself. `menuv` is a library and can only be used in other resources.

Please try again with this resource: 
[menuv_example.zip](https://github.com/ThymonA/menuv/files/5760386/menuv_example.zip)

**Comment by TopZoozle** [comment]
Ahh I see, I am not sure if I am the only person who didn't realise, Might be worth noting on the ReadMe.

Seems to be working perfectly now!


P.S Thank you for all the hardwork! The performance difference between this and something like Native / vMenu is something I've been looking for!.
