### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by TopZoozle** [ThymonA/menuv#18]
I know this isn't a issue but I honestly didn't know where to post for request / ideas

I checked through the Documentation and I didn't see anything about allowing for controller inputs. is this something that can be done or is it something that needs to be added to the API?

**Comment by ThymonA** [comment]
You mean like a text input etc?

**Comment by Korioz** [comment]
I think he is talking about controlling the menu with a controller, like xbox controllers.
Gonna do some reasearch to have valid key mapping info, will do a PR as soon it's ready.

**Comment by Korioz** [comment]
Added it in pr #20 & some other things 🙂

**Comment by ThymonA** [comment]
Controller support has been added in [ #20 ] and has been committed to [ [`master`](https://github.com/ThymonA/menuv/tree/master) ] on commit [ c5758aeb9138d24c80756cd857199ff7fc15c99b ]
