### ISSUE TITLE
List of valid keys? and other questions/issues

### ISSUE THREAD

**Issue by Pesoen** [ThymonA/menuv#19]
I am trying to see if i can use this menu system to replace a very outdated, sluggish and horrible looking menu system on my server, but no matter what i change the key to in the example, it opens using F1.. tried removing the example.lua file from the menuv folder, and moving it to a separate folder, so i can begin testing stuff, and it still opens on f1, despite me changing it to other valid keys(del/delete, F2, F3, N and other random keys) is it possible to get a list of valid keys, and some kind of reason as to why it failsafe's back to F1? when i tried with del it said "[IO] Invalid key name DEL" and so far only the del key has made it state this, no matter what other keys i try..

it looks awesome, it seems simple enough to use, hence the reason i would like to switch to it instead of whatever thingy we are using now..

*EDIT*
of course just as i say this, i try with other weird key names, and now it states other keys as invalid(ins for instance) but it still only works on F1, regardless of whether it says invalid key or not..

Additional information:
Version of menuv: Latest(1.4)
Fivem Server Version: 3184.
Fivem Client Version: 3348
Tried keys(still opens on F1 regardless):
-Delete
-Insert
-F2
-F3
-End
-N
-G
-X
-E

Not yet tried:
-binding it to a chat command(opening the menu using a chat command, only tried using keybind for simplicity)
-binding it to a location(walking into a location opens it up using a trigger)

*EDIT 2*
i can now force the menu open on the key i want, using a small section in the code, copied from another script(IsControlJustReleased) so now i can force it to show on the key i want(still opens on F1 as well) but now another issue has come to my attention. i cannot close the menu again.. using a simple if statement to see if the menu is open(using a Boolean that follows it's state) i can select to either open or close the menu on the key i want. problem is the menu stays open..
tried using the debug code to print when something happened, and it does print the "menu closed" text i asked it to print, but the menu is still showing.

i can also not interact with the menu at all.. it shows and that's it.. mouse cursor is not showing up and stays showing.. gonna try(for fun and to see if that changes anything) to download an older version, and see if i can get that one working.. who knows, it might just work :)

*EDIT 3*
just noticed the "Close All" button, and it works to shut it down.. still odd that it otherwise refuses to work..

**Comment by Pesoen** [comment]
Using the older 1.3 version i can open and close the menu, and everything seems to work just fine.. gonna try the 1.4 version again in a second, see if it works now for some odd reason, who knows, it might just work :)

**Comment by Pesoen** [comment]
and now it works as well.. but it still does not close using the MenuV:CloseMenu(menu) thingy. but i can live with that since i can now close it using backspace and the "close all" keybind.. but would still like a list of keys to use, or should it work with the entire keyboard?

**Comment by Pesoen** [comment]
gonna stick with 1.3 for now.. since it seems to work flawlessly for me, so far.

**Comment by ThymonA** [comment]
[inputmappings-info.txt](https://github.com/ThymonA/menuv/files/5768796/inputmappings-info.txt)

**Comment by Pesoen** [comment]
awesome. should add that to the documentation for future reference.. now to try to find out why it forces F1 as the only key it will activate on when using the OpenWith command.. even tried binding it to the mouse, still opens on F1..(happens in 1.3 and 1.4)

**Comment by ThymonA** [comment]
The only place where F1 is binded is inside the **example.lua** file here https://github.com/ThymonA/menuv/blob/9ed05d19cf27d037f0c0d7b9deeeaef65300994f/example/example.lua#L45

You should be able to rebind it to another key, just remember than when a key is already added with the same name, overrising doesn't exisit. When the name and resource exists on the client, you can't change the keybond anymore and the user needs to do that.

You can also rename the resource or the namespace of the menu.

**Comment by Pesoen** [comment]
already tried that. tried for simplicity to rebind it to F2.. a clean install of a fivem server(for testing stuff before pushing it to our main server) is unable to change the key..

tried the following lines to try to change they key away from F1
-menu:OpenWith('MOUSE_BUTTON', 'MOUSE_MIDDLE')
-menu:OpenWith('keyboard', 'F2')
-menu:OpenWith('KEYBOARD', 'F2')
-menu:OpenWith('keyboard', 'DELETE')
-menu:OpenWith('keyboard', 'INSERT')

even with the changes, it still opens the demo menu on F1. complete shutdown and refresh of resources, clearing the cache, nothing has changed this keybind.. even set up another fresh server install with only the basics to get a fivem server running. copied over my altered version of the example(with an altered keybind) and it still opens on F1..

Also kinda fixed the example on my end anyway.... the button added on line 7 gets removed by the code on line 36. moved the code down under that line and now it shows as i think it was intended..

**Comment by ThymonA** [comment]
Rebinds are saved on the client and not on your server. Rebinds are saved based on the resource name and the command they execute. 
On the client, those keybinds are saved here:
```
%appdata%\CitizenFX\fivem.cfg
```
Example rebind is
```
rbind menuv_example KEYBOARD G "+25dae99d"
```
So you need to rename `menuv_example` to something else or rename the `namespace` to something else. You can also remove `rbind` row from the `fivem.cfg` to reset the `rbind`

**Comment by Pesoen** [comment]
ahh. that explains a few things.. i had three rbinds two set for F2(my test key) and one for F1, the F1 was the lowest in the list, so that explains why it was overwritten no matter what i did..

and now i can see that i can edit the key in game, which also helps a ton, this means i can now proceed with my menu overhaul on the server, so all menu's are based off of MenuV and it can all be accessed using a single keybind(making a unified menu system, so one keybind contains all underlying menu's and of course retaining keybinds for job specific menu's, but also adding a button for it in the unified menu)

Thanks for all the help, and sorry if i seemed to bother you, as that was not my intention.

time to get to coding my unified menu system and remove some keybinds :)

**Comment by ThymonA** [comment]
You can always ask me anything, I will try to explain as much a possible.
If you like to contact me on other ways, those are the options:

**GitHub:** ThymonA
**Discord:** Tigo#9999
**Mail:** contact@arens.io or contact@thymonarens.nl

Your always free to ask here or on the abovementioned ways.
