### ISSUE TITLE
Problem with a lot of items on the menu.

### ISSUE THREAD

**Issue by cristianrg36** [ThymonA/menuv#3]
Im making admin menu with menuv, but with players menu i have a problem when i have a lot of items i can scroll.
![image](https://user-images.githubusercontent.com/58856610/100634628-d54ced00-332f-11eb-859c-e3650d593b64.png)

I add the items manually. When the menu have more than 30/40 items i can't scroll to down.

**Comment by ThymonA** [comment]
I will fix this issue

**Comment by ThymonA** [comment]
This issue/bug has been fixed in (43869b68674a72efc77b1acdd3301abe0d7e5f87) -> [`master`](https://github.com/ThymonA/menuv/commits/master)
