### ISSUE TITLE
Clone Items [ERROR]

### ISSUE THREAD

**Issue by cristianrg36** [ThymonA/menuv#4]
I have a problem when i use for x = x do ( I use the example and i record a video for u )

Video: https://streamable.com/kzwtfq

**Comment by cristianrg36** [comment]
The buttons duplicates but it's random sometimes duplicates, sometimes no

**Comment by ThymonA** [comment]
Did you use the latest version, because it should already been fixed: 44bdf01ef07b0d8f4578ae1fd2708e04664abbd0 ?

**Comment by cristianrg36** [comment]
Oh, i testing the new version and error fixed. Sorry i don't see the update 44bf01 ^^

**Comment by ThymonA** [comment]
No problem, keep making issues if you think there is a bug or a missing feature.
