### ISSUE TITLE
Script dependencies

### ISSUE THREAD

**Issue by PhoenixGamer339** [ThymonA/menuv#54]
Hey,
does menuv have a dependency? 

I want to use the libary for my scripts and want to make sure menuv is installed

( @ThymonA  )

**Comment by PhoenixGamer339** [comment]
So you can´t leave an dependency in your own scripts @Mobius1

**Comment by SkylarPlayz348** [comment]
@PhoenixGamer339 All you need to do is make sure MenuV is started before that script and have `@menuv/menuv.lua` at the top your client scripts in the fxmanifest. Anyone correct me if I'm wrong

**Comment by PhoenixGamer339** [comment]
Thanks :)
